// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/admin.tsx";
import * as $3 from "./routes/api/form/listen.ts";
import * as $4 from "./routes/api/form/update.ts";
import * as $5 from "./routes/api/joke.ts";
import * as $6 from "./routes/athlete.tsx";
import * as $7 from "./routes/greet/[name].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/indexold.tsx";
import * as $10 from "./routes/judge.tsx";
import * as $11 from "./routes/leaderboard.tsx";
import * as $12 from "./routes/scan-qr.tsx";
import * as $13 from "./routes/search.tsx";
import * as $14 from "./routes/settings.tsx";
import * as $15 from "./routes/settings2.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/SearchName.tsx";
import * as $$2 from "./islands/Topout.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/admin.tsx": $2,
    "./routes/api/form/listen.ts": $3,
    "./routes/api/form/update.ts": $4,
    "./routes/api/joke.ts": $5,
    "./routes/athlete.tsx": $6,
    "./routes/greet/[name].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/indexold.tsx": $9,
    "./routes/judge.tsx": $10,
    "./routes/leaderboard.tsx": $11,
    "./routes/scan-qr.tsx": $12,
    "./routes/search.tsx": $13,
    "./routes/settings.tsx": $14,
    "./routes/settings2.tsx": $15,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/SearchName.tsx": $$1,
    "./islands/Topout.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
